<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(DefaultTargetFrameworks)</TargetFrameworks>

		<OutputPath>..\..\_output\$(FrameworkPath)\$(AssemblyName)</OutputPath>
		<IntermediateOutputPath>..\..\_obj\$(FrameworkPath)\$(AssemblyName)</IntermediateOutputPath>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	</PropertyGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\SpringCard.PCSC\SpringCard.PCSC.csproj" />
  </ItemGroup>
	
  <ItemGroup Condition="$(TargetFramework) == 'net48'">
		<PackageReference Include="SpringCard.Bluetooth" />
  </ItemGroup>
	
	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="" />
		<None Include="..\LICENSE.txt" Pack="true" PackagePath="" />
	</ItemGroup>

</Project>